name: CI

on:
  push:
    branches: ["main", "1stLab"]
  pull_request:
    branches: ["main", "1stLab"]

jobs:
  build-and-test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        run: sudo apt-get update -qq && sudo apt-get install -y cmake ninja-build libgtest-dev
      - name: Show repository files
        run: find . -name CMakeLists.txt -print
      - name: Configure
        run: cmake -S ./lab1/Set -B build -G Ninja
      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure